version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mynet
  
  pg4admin:
    image: dpage/pgadmin4
    container_name: pg4admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    networks:
      - mynet
    
  grpcserver:
    image: grpcserver
    container_name: grpcserver
    ports:
      - "5117:80"
    environment:
      ASPNETCORE_URLS: "http://+:80"
    depends_on:
      - postgres
    networks:
      - mynet
  
  restserver:
    image: restserver
    container_name: restserver
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - mynet
  
networks:
  mynet:
    driver: bridge