// <auto-generated />
using System;
using GrpcServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrpcServer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240407180932_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrpcServer.PondData", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntryId"));

                    b.Property<float>("AmmoniaGMl")
                        .HasColumnType("real");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("DissolvedOxygenGMl")
                        .HasColumnType("real");

                    b.Property<float>("FishLengthCm")
                        .HasColumnType("real");

                    b.Property<float>("FishWeightG")
                        .HasColumnType("real");

                    b.Property<float>("NitriteGMl")
                        .HasColumnType("real");

                    b.Property<float>("Ph")
                        .HasColumnType("real");

                    b.Property<int>("PondId")
                        .HasColumnType("integer");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<float>("TempC")
                        .HasColumnType("real");

                    b.Property<int>("TurbidityNtu")
                        .HasColumnType("integer");

                    b.HasKey("EntryId");

                    b.ToTable("PondData");
                });
#pragma warning restore 612, 618
        }
    }
}
